package Chat;

/**
* Chat/ClientChatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* dimanche 2 avril 2017 10 h 27 CEST
*/

public final class ClientChatHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.ClientChat value = null;

  public ClientChatHolder ()
  {
  }

  public ClientChatHolder (Chat.ClientChat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.ClientChatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.ClientChatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.ClientChatHelper.type ();
  }

}
