package Chat;


/**
* Chat/ClientChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* dimanche 2 avril 2017 10 h 27 CEST
*/

public interface ClientChatOperations 
{
  void receiveNewChatter (String name);
  void receiveExitChatter (String name);
  void receiveChat (String name, String message);
} // interface ClientChatOperations
