package Chat;


/**
* Chat/ClientChatPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* dimanche 2 avril 2017 10 h 27 CEST
*/

public abstract class ClientChatPOA extends org.omg.PortableServer.Servant
 implements Chat.ClientChatOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("receiveNewChatter", new java.lang.Integer (0));
    _methods.put ("receiveExitChatter", new java.lang.Integer (1));
    _methods.put ("receiveChat", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Chat/ClientChat/receiveNewChatter
       {
         String name = in.read_string ();
         this.receiveNewChatter (name);
         out = $rh.createReply();
         break;
       }

       case 1:  // Chat/ClientChat/receiveExitChatter
       {
         String name = in.read_string ();
         this.receiveExitChatter (name);
         out = $rh.createReply();
         break;
       }

       case 2:  // Chat/ClientChat/receiveChat
       {
         String name = in.read_string ();
         String message = in.read_string ();
         this.receiveChat (name, message);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Chat/ClientChat:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ClientChat _this() 
  {
    return ClientChatHelper.narrow(
    super._this_object());
  }

  public ClientChat _this(org.omg.CORBA.ORB orb) 
  {
    return ClientChatHelper.narrow(
    super._this_object(orb));
  }


} // class ClientChatPOA
