package Chat;

/**
* Chat/ServeurChatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* dimanche 2 avril 2017 10 h 27 CEST
*/

public final class ServeurChatHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.ServeurChat value = null;

  public ServeurChatHolder ()
  {
  }

  public ServeurChatHolder (Chat.ServeurChat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.ServeurChatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.ServeurChatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.ServeurChatHelper.type ();
  }

}
