package Chat;


/**
* Chat/ServeurChatPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* dimanche 2 avril 2017 10 h 27 CEST
*/

public abstract class ServeurChatPOA extends org.omg.PortableServer.Servant
 implements Chat.ServeurChatOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("login", new java.lang.Integer (0));
    _methods.put ("logout", new java.lang.Integer (1));
    _methods.put ("broadcast", new java.lang.Integer (2));
    _methods.put ("chat", new java.lang.Integer (3));
    _methods.put ("whoIsLogged", new java.lang.Integer (4));
    _methods.put ("ping", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Chat/ServeurChat/login
       {
         String name = in.read_string ();
         Chat.ClientChat chatter = Chat.ClientChatHelper.read (in);
         this.login (name, chatter);
         out = $rh.createReply();
         break;
       }

       case 1:  // Chat/ServeurChat/logout
       {
         String name = in.read_string ();
         this.logout (name);
         out = $rh.createReply();
         break;
       }

       case 2:  // Chat/ServeurChat/broadcast
       {
         String name = in.read_string ();
         String message = in.read_string ();
         this.broadcast (name, message);
         out = $rh.createReply();
         break;
       }

       case 3:  // Chat/ServeurChat/chat
       {
         String myname = in.read_string ();
         String hisname = in.read_string ();
         String message = in.read_string ();
         this.chat (myname, hisname, message);
         out = $rh.createReply();
         break;
       }

       case 4:  // Chat/ServeurChat/whoIsLogged
       {
         String $result = null;
         $result = this.whoIsLogged ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // Chat/ServeurChat/ping
       {
         String $result = null;
         $result = this.ping ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Chat/ServeurChat:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServeurChat _this() 
  {
    return ServeurChatHelper.narrow(
    super._this_object());
  }

  public ServeurChat _this(org.omg.CORBA.ORB orb) 
  {
    return ServeurChatHelper.narrow(
    super._this_object(orb));
  }


} // class ServeurChatPOA
