package Chat;


/**
* Chat/UserInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* dimanche 2 avril 2017 10 h 27 CEST
*/

abstract public class UserInfoHelper
{
  private static String  _id = "IDL:Chat/UserInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, Chat.UserInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Chat.UserInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = Chat.ClientChatHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "chatter",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (Chat.UserInfoHelper.id (), "UserInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Chat.UserInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    Chat.UserInfo value = new Chat.UserInfo ();
    value.name = istream.read_string ();
    value.chatter = Chat.ClientChatHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Chat.UserInfo value)
  {
    ostream.write_string (value.name);
    Chat.ClientChatHelper.write (ostream, value.chatter);
  }

}
