package Chat;

/**
* Chat/UserInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* dimanche 2 avril 2017 10 h 27 CEST
*/

public final class UserInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public Chat.UserInfo value = null;

  public UserInfoHolder ()
  {
  }

  public UserInfoHolder (Chat.UserInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Chat.UserInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Chat.UserInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Chat.UserInfoHelper.type ();
  }

}
