module Gimme
{
  struct GameInfos
  {
    boolean taketurns ;
    boolean running ;
  } ;

   
  interface Producer
  {
    long getResource(in long amount) ;
    long queryAmount() ;
  } ;


  interface Consumer
  {
  typedef sequence<Producer> TabProd;
  typedef sequence<Consumer> TabCons;
    long start(in TabProd p, in TabCons c) ;
    void hello() ; // test
  } ;


  interface Coordinator
  {
    long loginConsumer(in Consumer c) ;
    long loginProducer(in Producer p) ;
    GameInfos getGameInfos();
  } ;

} ;
