module Gimme
{
  struct GameInfos
  {
    boolean taketurns ;
    boolean running ;
  } ;

  
  interface Agent
  {
  // TODO insert common methods here
    void logmsg(in string msg, in long type);
  } ; 

  interface Producer : Agent
  {
    long getResource(in long amount) ;
    long queryAmount() ;
  } ;


  interface Consumer : Agent
  {
  typedef sequence<Producer> TabProd;
  typedef sequence<Consumer> TabCons;
    long start(in TabProd p, in TabCons c) ;
    void hello() ; // test
  } ;


  interface Coordinator
  {
    long loginConsumer(in Consumer c) ;
    long loginProducer(in Producer p) ;
    GameInfos getGameInfos();
  } ;

} ;
