#!/bin/sh

HOST=localhost
PORT=8921
CHOICE=$1
shift

set -x
case $CHOICE in
    1) tnameserv -ORBInitialPort $PORT  ;;
    2) java CoordinatorImpl $HOST $PORT $@ ;;  
    3) java ConsumerImpl $HOST $PORT $@ ;;
    4) java ProducerImpl $HOST $PORT $@ ;;
esac
