module Chat
{
  interface ClientChat
  {
    oneway void receiveNewChatter(in string name) ;
    oneway void receiveExitChatter(in string name) ;
    oneway void receiveChat(in string name, in string message) ;
  } ;

  struct UserInfo
  {
    string name ;
    ClientChat chatter ;
  } ;

  interface ServeurChat
  {
    oneway void login(in string name, in ClientChat chatter) ;
    oneway void logout(in string name) ;
    oneway void broadcast(in string name, in string message) ;
    oneway void chat(in string myname, in string hisname, in string message) ;
    string whoIsLogged() ;
    string ping() ;
  } ;

} ;
